// react-project/src/App.jsx
import React, { Component } from 'react';

class App extends Component {
  state = {
    users: [],
    isLoading: false,
  }

  renderUsersList() {
    return this.state.users.map((user, index) => {
      return (
        <li className="container-list--item" key={index}>
          <p>{user.name}</p>
          <span>{user.email}</span>
        </li>
      );
    });
  }

  render() {
    return (
      <div className="container">
      {
        this.state.isLoading
          ? (
            <div className="loading">
              <div className="loading-spinner"></div>
            </div>
          ) : null
      }

      <h1 className="container-title">The Amazing App! <span aria-label="img" role="img">😍</span></h1>
      <ul className="container-list">{this.renderUsersList()}</ul>
    </div>
    )
  }
}

export default App;

// vue-project/src/App.vue
<template>
  <div class="container">
    <div class="loading" v-if="isLoading">
      <div class="loading-spinner"></div>
    </div>
     <h1 class="container-title">The Amazing App! 😍</h1>
    <ul class="container-list">
      <li class="container-list--item" v-for="(user, index) in users" :key="index">
        <p>{{ user.name }}</p>
        <span>{{ user.email }}</span>
      </li>
    </ul>
  </div>
</template>

<script>
import { mapActions, mapState } from 'vuex';

export default {
  name: 'app',
  computed: {
    ...mapState({
      isLoading: state => state.isLoading,
      users: state => state.users,
    }),
  },
  created() {
    this.fetchUsers()
  },
  methods: {
    ...mapActions(['fetchUsers'])
  }
}
</script>

<style>
@import url('./style.css');
</style>
